<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Platforms>AnyCPU</Platforms>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
