/* Generated by GenerateCS_APObject */
using System.Collections.Generic;

namespace CupheadArchipelago.AP {
    public abstract class APObject {
        public long Id { get; private set; }

        public APObject(long id) {
            Id = id;
        }

        public static implicit operator long(APObject a) => a.Id;
        public override string ToString() { return $"APObject {Id}"; }
    }

    public class APItem : APObject {
        private static readonly Dictionary<long,APItem> id_map = new();
        public APItem(long id) : base(id) { id_map.Add(id,this); }

        public static readonly APItem level_present = new APItem(0xc4ead0);
        public static readonly APItem level_extrahealth = new APItem(0xc4ead1);
        public static readonly APItem level_superrecharge = new APItem(0xc4ead2);
        public static readonly APItem coin = new APItem(0xc4ead3);
        public static readonly APItem coin2 = new APItem(0xc4ead4);
        public static readonly APItem coin3 = new APItem(0xc4ead5);
        public static readonly APItem plane_gun = new APItem(0xc4ead6);
        public static readonly APItem plane_bombs = new APItem(0xc4ead7);
        public static readonly APItem plane_super = new APItem(0xc4ead8);
        public static readonly APItem contract = new APItem(0xc4ead9);
        public static readonly APItem weapon_peashooter = new APItem(0xc4eada);
        public static readonly APItem weapon_spread = new APItem(0xc4eadb);
        public static readonly APItem weapon_chaser = new APItem(0xc4eadc);
        public static readonly APItem weapon_lobber = new APItem(0xc4eadd);
        public static readonly APItem weapon_charge = new APItem(0xc4eade);
        public static readonly APItem weapon_roundabout = new APItem(0xc4eadf);
        public static readonly APItem charm_heart = new APItem(0xc4eae0);
        public static readonly APItem charm_smokebomb = new APItem(0xc4eae1);
        public static readonly APItem charm_psugar = new APItem(0xc4eae2);
        public static readonly APItem charm_coffee = new APItem(0xc4eae3);
        public static readonly APItem charm_twinheart = new APItem(0xc4eae4);
        public static readonly APItem charm_whetstone = new APItem(0xc4eae5);
        public static readonly APItem super_i = new APItem(0xc4eae6);
        public static readonly APItem super_ii = new APItem(0xc4eae7);
        public static readonly APItem super_iii = new APItem(0xc4eae8);
        public static readonly APItem ability_duck = new APItem(0xc4eae9);
        public static readonly APItem ability_dash = new APItem(0xc4eaea);
        public static readonly APItem ability_parry = new APItem(0xc4eaeb);
        public static readonly APItem ability_plane_shrink = new APItem(0xc4eaec);
        public static readonly APItem ability_plane_parry = new APItem(0xc4eaed);
        public static readonly APItem ability_aim_left = new APItem(0xc4eaee);
        public static readonly APItem ability_aim_right = new APItem(0xc4eaef);
        public static readonly APItem ability_aim_up = new APItem(0xc4eaf0);
        public static readonly APItem ability_aim_down = new APItem(0xc4eaf1);
        public static readonly APItem ability_aim_upleft = new APItem(0xc4eaf2);
        public static readonly APItem ability_aim_upright = new APItem(0xc4eaf3);
        public static readonly APItem ability_aim_downleft = new APItem(0xc4eaf4);
        public static readonly APItem ability_aim_downright = new APItem(0xc4eaf5);
        public static readonly APItem level_trap_fingerjam = new APItem(0xc4eaf6);
        public static readonly APItem level_trap_slowfire = new APItem(0xc4eaf7);
        public static readonly APItem level_trap_superdrain = new APItem(0xc4eaf8);
        public static readonly APItem level_trap_envirotrap = new APItem(0xc4eaf9);
        public static readonly APItem dlc_boat = new APItem(0xc4fad0);
        public static readonly APItem dlc_ingredient = new APItem(0xc4fad1);
        public static readonly APItem weapon_dlc_crackshot = new APItem(0xc4fad2);
        public static readonly APItem weapon_dlc_converge = new APItem(0xc4fad3);
        public static readonly APItem weapon_dlc_twistup = new APItem(0xc4fad4);
        public static readonly APItem charm_dlc_cookie = new APItem(0xc4fad5);
        public static readonly APItem charm_dlc_heartring = new APItem(0xc4fad6);
        public static readonly APItem charm_dlc_broken_relic = new APItem(0xc4fad7);

        public static APItem FromId(long id) => id_map[id];
        public static bool IdExists(long id) => id_map.ContainsKey(id);
        public override string ToString() { return $"APItem {Id}"; }
    }

    public class APLocation : APObject {
        private static readonly Dictionary<long,APLocation> id_map = new();
        public APLocation(long id) : base(id) { id_map.Add(id,this); }

        public static readonly APLocation level_tutorial = new APLocation(0xc4ead0);
        public static readonly APLocation level_tutorial_coin = new APLocation(0xc4ead1);
        public static readonly APLocation level_boss_veggies = new APLocation(0xc4ead3);
        public static readonly APLocation level_boss_veggies_topgrade = new APLocation(0xc4ead4);
        public static readonly APLocation level_boss_slime = new APLocation(0xc4ead5);
        public static readonly APLocation level_boss_slime_topgrade = new APLocation(0xc4ead6);
        public static readonly APLocation level_boss_frogs = new APLocation(0xc4ead7);
        public static readonly APLocation level_boss_frogs_topgrade = new APLocation(0xc4ead8);
        public static readonly APLocation level_boss_flower = new APLocation(0xc4ead9);
        public static readonly APLocation level_boss_flower_topgrade = new APLocation(0xc4eada);
        public static readonly APLocation level_boss_baroness = new APLocation(0xc4eadb);
        public static readonly APLocation level_boss_baroness_topgrade = new APLocation(0xc4eadc);
        public static readonly APLocation level_boss_clown = new APLocation(0xc4eadd);
        public static readonly APLocation level_boss_clown_topgrade = new APLocation(0xc4eade);
        public static readonly APLocation level_boss_dragon = new APLocation(0xc4eadf);
        public static readonly APLocation level_boss_dragon_topgrade = new APLocation(0xc4eae0);
        public static readonly APLocation level_boss_bee = new APLocation(0xc4eae1);
        public static readonly APLocation level_boss_bee_topgrade = new APLocation(0xc4eae2);
        public static readonly APLocation level_boss_pirate = new APLocation(0xc4eae3);
        public static readonly APLocation level_boss_pirate_topgrade = new APLocation(0xc4eae4);
        public static readonly APLocation level_boss_mouse = new APLocation(0xc4eae5);
        public static readonly APLocation level_boss_mouse_topgrade = new APLocation(0xc4eae6);
        public static readonly APLocation level_boss_sallystageplay = new APLocation(0xc4eae7);
        public static readonly APLocation level_boss_sallystageplay_topgrade = new APLocation(0xc4eae8);
        public static readonly APLocation level_boss_train = new APLocation(0xc4eae9);
        public static readonly APLocation level_boss_train_topgrade = new APLocation(0xc4eaea);
        public static readonly APLocation level_boss_kingdice = new APLocation(0xc4eaeb);
        public static readonly APLocation level_boss_kingdice_topgrade = new APLocation(0xc4eaec);
        public static readonly APLocation level_boss_plane_blimp = new APLocation(0xc4eaed);
        public static readonly APLocation level_boss_plane_blimp_topgrade = new APLocation(0xc4eaee);
        public static readonly APLocation level_boss_plane_genie = new APLocation(0xc4eaef);
        public static readonly APLocation level_boss_plane_genie_topgrade = new APLocation(0xc4eaf0);
        public static readonly APLocation level_boss_plane_bird = new APLocation(0xc4eaf1);
        public static readonly APLocation level_boss_plane_bird_topgrade = new APLocation(0xc4eaf2);
        public static readonly APLocation level_boss_plane_mermaid = new APLocation(0xc4eaf3);
        public static readonly APLocation level_boss_plane_mermaid_topgrade = new APLocation(0xc4eaf4);
        public static readonly APLocation level_boss_plane_robot = new APLocation(0xc4eaf5);
        public static readonly APLocation level_boss_plane_robot_topgrade = new APLocation(0xc4eaf6);
        public static readonly APLocation level_dicepalace_boss_booze = new APLocation(0xc4eaf9);
        public static readonly APLocation level_dicepalace_boss_chips = new APLocation(0xc4eafa);
        public static readonly APLocation level_dicepalace_boss_cigar = new APLocation(0xc4eafb);
        public static readonly APLocation level_dicepalace_boss_domino = new APLocation(0xc4eafc);
        public static readonly APLocation level_dicepalace_boss_rabbit = new APLocation(0xc4eafd);
        public static readonly APLocation level_dicepalace_boss_plane_horse = new APLocation(0xc4eafe);
        public static readonly APLocation level_dicepalace_boss_roulette = new APLocation(0xc4eaff);
        public static readonly APLocation level_dicepalace_boss_eightball = new APLocation(0xc4eb00);
        public static readonly APLocation level_dicepalace_boss_plane_memory = new APLocation(0xc4eb01);
        public static readonly APLocation level_rungun_forest = new APLocation(0xc4eb02);
        public static readonly APLocation level_rungun_forest_agrade = new APLocation(0xc4eb03);
        public static readonly APLocation level_rungun_forest_pacifist = new APLocation(0xc4eb04);
        public static readonly APLocation level_rungun_forest_coin1 = new APLocation(0xc4eb05);
        public static readonly APLocation level_rungun_forest_coin2 = new APLocation(0xc4eb06);
        public static readonly APLocation level_rungun_forest_coin3 = new APLocation(0xc4eb07);
        public static readonly APLocation level_rungun_forest_coin4 = new APLocation(0xc4eb08);
        public static readonly APLocation level_rungun_forest_coin5 = new APLocation(0xc4eb09);
        public static readonly APLocation level_rungun_tree = new APLocation(0xc4eb0a);
        public static readonly APLocation level_rungun_tree_agrade = new APLocation(0xc4eb0b);
        public static readonly APLocation level_rungun_tree_pacifist = new APLocation(0xc4eb0c);
        public static readonly APLocation level_rungun_tree_coin1 = new APLocation(0xc4eb0d);
        public static readonly APLocation level_rungun_tree_coin2 = new APLocation(0xc4eb0e);
        public static readonly APLocation level_rungun_tree_coin3 = new APLocation(0xc4eb0f);
        public static readonly APLocation level_rungun_tree_coin4 = new APLocation(0xc4eb10);
        public static readonly APLocation level_rungun_tree_coin5 = new APLocation(0xc4eb11);
        public static readonly APLocation level_rungun_circus = new APLocation(0xc4eb12);
        public static readonly APLocation level_rungun_circus_agrade = new APLocation(0xc4eb13);
        public static readonly APLocation level_rungun_circus_pacifist = new APLocation(0xc4eb14);
        public static readonly APLocation level_rungun_circus_coin1 = new APLocation(0xc4eb15);
        public static readonly APLocation level_rungun_circus_coin2 = new APLocation(0xc4eb16);
        public static readonly APLocation level_rungun_circus_coin3 = new APLocation(0xc4eb17);
        public static readonly APLocation level_rungun_circus_coin4 = new APLocation(0xc4eb18);
        public static readonly APLocation level_rungun_circus_coin5 = new APLocation(0xc4eb19);
        public static readonly APLocation level_rungun_funhouse = new APLocation(0xc4eb1a);
        public static readonly APLocation level_rungun_funhouse_agrade = new APLocation(0xc4eb1b);
        public static readonly APLocation level_rungun_funhouse_pacifist = new APLocation(0xc4eb1c);
        public static readonly APLocation level_rungun_funhouse_coin1 = new APLocation(0xc4eb1d);
        public static readonly APLocation level_rungun_funhouse_coin2 = new APLocation(0xc4eb1e);
        public static readonly APLocation level_rungun_funhouse_coin3 = new APLocation(0xc4eb1f);
        public static readonly APLocation level_rungun_funhouse_coin4 = new APLocation(0xc4eb20);
        public static readonly APLocation level_rungun_funhouse_coin5 = new APLocation(0xc4eb21);
        public static readonly APLocation level_rungun_harbour = new APLocation(0xc4eb22);
        public static readonly APLocation level_rungun_harbour_agrade = new APLocation(0xc4eb23);
        public static readonly APLocation level_rungun_harbour_pacifist = new APLocation(0xc4eb24);
        public static readonly APLocation level_rungun_harbour_coin1 = new APLocation(0xc4eb25);
        public static readonly APLocation level_rungun_harbour_coin2 = new APLocation(0xc4eb26);
        public static readonly APLocation level_rungun_harbour_coin3 = new APLocation(0xc4eb27);
        public static readonly APLocation level_rungun_harbour_coin4 = new APLocation(0xc4eb28);
        public static readonly APLocation level_rungun_harbour_coin5 = new APLocation(0xc4eb29);
        public static readonly APLocation level_rungun_mountain = new APLocation(0xc4eb2a);
        public static readonly APLocation level_rungun_mountain_agrade = new APLocation(0xc4eb2b);
        public static readonly APLocation level_rungun_mountain_pacifist = new APLocation(0xc4eb2c);
        public static readonly APLocation level_rungun_mountain_coin1 = new APLocation(0xc4eb2d);
        public static readonly APLocation level_rungun_mountain_coin2 = new APLocation(0xc4eb2e);
        public static readonly APLocation level_rungun_mountain_coin3 = new APLocation(0xc4eb2f);
        public static readonly APLocation level_rungun_mountain_coin4 = new APLocation(0xc4eb30);
        public static readonly APLocation level_rungun_mountain_coin5 = new APLocation(0xc4eb31);
        public static readonly APLocation level_mausoleum_i = new APLocation(0xc4eb32);
        public static readonly APLocation level_mausoleum_ii = new APLocation(0xc4eb33);
        public static readonly APLocation level_mausoleum_iii = new APLocation(0xc4eb34);
        public static readonly APLocation shop_weapon1 = new APLocation(0xc4eb35);
        public static readonly APLocation shop_weapon2 = new APLocation(0xc4eb36);
        public static readonly APLocation shop_weapon3 = new APLocation(0xc4eb37);
        public static readonly APLocation shop_weapon4 = new APLocation(0xc4eb38);
        public static readonly APLocation shop_weapon5 = new APLocation(0xc4eb39);
        public static readonly APLocation shop_charm1 = new APLocation(0xc4eb3a);
        public static readonly APLocation shop_charm2 = new APLocation(0xc4eb3b);
        public static readonly APLocation shop_charm3 = new APLocation(0xc4eb3c);
        public static readonly APLocation shop_charm4 = new APLocation(0xc4eb3d);
        public static readonly APLocation shop_charm5 = new APLocation(0xc4eb3e);
        public static readonly APLocation shop_charm6 = new APLocation(0xc4eb3f);
        public static readonly APLocation npc_mac = new APLocation(0xc4eb40);
        public static readonly APLocation npc_canteen = new APLocation(0xc4eb41);
        public static readonly APLocation coin_isle1_secret = new APLocation(0xc4eb42);
        public static readonly APLocation coin_isle2_secret = new APLocation(0xc4eb43);
        public static readonly APLocation coin_isle3_secret = new APLocation(0xc4eb44);
        public static readonly APLocation coin_isleh_secret = new APLocation(0xc4eb45);
        public static readonly APLocation quest_4parries = new APLocation(0xc4eb46);
        public static readonly APLocation quest_ginger = new APLocation(0xc4eb47);
        public static readonly APLocation quest_4mel = new APLocation(0xc4eb48);
        public static readonly APLocation quest_lucien = new APLocation(0xc4eb49);
        public static readonly APLocation quest_pacifist = new APLocation(0xc4eb4a);
        public static readonly APLocation quest_15agrades = new APLocation(0xc4eb4b);
        public static readonly APLocation quest_ludwig = new APLocation(0xc4eb4c);
        public static readonly APLocation quest_wolfgang = new APLocation(0xc4eb4d);
        public static readonly APLocation level_dlc_tutorial = new APLocation(0xc4fad0);
        public static readonly APLocation level_dlc_tutorial_coin = new APLocation(0xc4fad1);
        public static readonly APLocation level_boss_veggies_dlc_chaliced = new APLocation(0xc4fad2);
        public static readonly APLocation level_boss_slime_dlc_chaliced = new APLocation(0xc4fad3);
        public static readonly APLocation level_boss_frogs_dlc_chaliced = new APLocation(0xc4fad4);
        public static readonly APLocation level_boss_flower_dlc_chaliced = new APLocation(0xc4fad5);
        public static readonly APLocation level_boss_baroness_dlc_chaliced = new APLocation(0xc4fad6);
        public static readonly APLocation level_boss_clown_dlc_chaliced = new APLocation(0xc4fad7);
        public static readonly APLocation level_boss_dragon_dlc_chaliced = new APLocation(0xc4fad8);
        public static readonly APLocation level_boss_bee_dlc_chaliced = new APLocation(0xc4fad9);
        public static readonly APLocation level_boss_pirate_dlc_chaliced = new APLocation(0xc4fada);
        public static readonly APLocation level_boss_mouse_dlc_chaliced = new APLocation(0xc4fadb);
        public static readonly APLocation level_boss_sallystageplay_dlc_chaliced = new APLocation(0xc4fadc);
        public static readonly APLocation level_boss_train_dlc_chaliced = new APLocation(0xc4fadd);
        public static readonly APLocation level_boss_kingdice_dlc_chaliced = new APLocation(0xc4fade);
        public static readonly APLocation level_boss_plane_blimp_dlc_chaliced = new APLocation(0xc4fadf);
        public static readonly APLocation level_boss_plane_genie_dlc_chaliced = new APLocation(0xc4fae0);
        public static readonly APLocation level_boss_plane_bird_dlc_chaliced = new APLocation(0xc4fae1);
        public static readonly APLocation level_boss_plane_mermaid_dlc_chaliced = new APLocation(0xc4fae2);
        public static readonly APLocation level_boss_plane_robot_dlc_chaliced = new APLocation(0xc4fae3);
        public static readonly APLocation level_dlc_boss_oldman = new APLocation(0xc4fae5);
        public static readonly APLocation level_dlc_boss_oldman_topgrade = new APLocation(0xc4fae6);
        public static readonly APLocation level_dlc_boss_oldman_dlc_chaliced = new APLocation(0xc4fae7);
        public static readonly APLocation level_dlc_boss_rumrunners = new APLocation(0xc4fae8);
        public static readonly APLocation level_dlc_boss_rumrunners_topgrade = new APLocation(0xc4fae9);
        public static readonly APLocation level_dlc_boss_rumrunners_dlc_chaliced = new APLocation(0xc4faea);
        public static readonly APLocation level_dlc_boss_snowcult = new APLocation(0xc4faeb);
        public static readonly APLocation level_dlc_boss_snowcult_topgrade = new APLocation(0xc4faec);
        public static readonly APLocation level_dlc_boss_snowcult_dlc_chaliced = new APLocation(0xc4faed);
        public static readonly APLocation level_dlc_boss_airplane = new APLocation(0xc4faee);
        public static readonly APLocation level_dlc_boss_airplane_topgrade = new APLocation(0xc4faef);
        public static readonly APLocation level_dlc_boss_airplane_dlc_chaliced = new APLocation(0xc4faf0);
        public static readonly APLocation level_dlc_boss_plane_cowboy = new APLocation(0xc4faf1);
        public static readonly APLocation level_dlc_boss_plane_cowboy_topgrade = new APLocation(0xc4faf2);
        public static readonly APLocation level_dlc_boss_plane_cowboy_dlc_chaliced = new APLocation(0xc4faf3);
        public static readonly APLocation level_dlc_chesscastle_run = new APLocation(0xc4faf7);
        public static readonly APLocation level_dlc_chesscastle_pawn = new APLocation(0xc4faf8);
        public static readonly APLocation level_dlc_chesscastle_knight = new APLocation(0xc4faf9);
        public static readonly APLocation level_dlc_chesscastle_bishop = new APLocation(0xc4fafa);
        public static readonly APLocation level_dlc_chesscastle_rook = new APLocation(0xc4fafb);
        public static readonly APLocation level_dlc_chesscastle_queen = new APLocation(0xc4fafc);
        public static readonly APLocation level_dlc_graveyard = new APLocation(0xc4fafd);
        public static readonly APLocation shop_dlc_weapon6 = new APLocation(0xc4fafe);
        public static readonly APLocation shop_dlc_weapon7 = new APLocation(0xc4faff);
        public static readonly APLocation shop_dlc_weapon8 = new APLocation(0xc4fb00);
        public static readonly APLocation shop_dlc_charm7 = new APLocation(0xc4fb01);
        public static readonly APLocation shop_dlc_charm8 = new APLocation(0xc4fb02);
        public static readonly APLocation dlc_npc_newscat = new APLocation(0xc4fb04);
        public static readonly APLocation dlc_coin_isle4_secret = new APLocation(0xc4fb05);
        public static readonly APLocation dlc_quest_cactusgirl = new APLocation(0xc4fb07);

        public static APLocation FromId(long id) => id_map[id];
        public static bool IdExists(long id) => id_map.ContainsKey(id);
        public override string ToString() { return $"APLocation {Id}"; }
    }
}
