name: Check Hooks

on:
  pull_request:
    paths:
      - "CupheadArchipelago/Hooks/**.cs"
      - ".github/check-hooks.py"
      - ".github/workflows/check-hooks.yml"
  push:
    paths:
      - "CupheadArchipelago/Hooks/**.cs"
      - ".github/check-hooks.py"
      - ".github/workflows/check-hooks.yml"

jobs:
  consistency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run HarmonyPatch consistency check
        run: |
          python .github/check-hooks.py ./CupheadArchipelago/Hooks
