name: Release

on:
  push:
    tags:
      - 'test*'
      - 'preview*'
      - '*.*.*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          name: Preview (${{ env.RELEASE_VERSION }})
        env:
          GITHUB_TOKEN: ${{ secrets.AP_TOKEN }}
